export const api = {
    "swagger": "2.0",
    "info": {
        "description": "This is a dynamic API generated by PostgREST",
        "title": "PostgREST API",
        "version": "12.0.2 (a4e00ff)"
    },
    "host": "xupzhicrqmyvtgztrmjb.supabase.co:443",
    "basePath": "/",
    "schemes": ["https"],
    "consumes": ["application/json", "application/vnd.pgrst.object+json;nulls=stripped", "application/vnd.pgrst.object+json", "text/csv"],
    "produces": ["application/json", "application/vnd.pgrst.object+json;nulls=stripped", "application/vnd.pgrst.object+json", "text/csv"],
    "paths": {
        "/": {
            "get": {
                "produces": ["application/openapi+json", "application/json"],
                "responses": {"200": {"description": "OK"}},
                "summary": "OpenAPI description (this document)",
                "tags": ["Introspection"]
            }
        },
        "/orderline": {
            "get": {
                "parameters": [{"$ref": "#/parameters/rowFilter.orderline.id"}, {"$ref": "#/parameters/rowFilter.orderline.owner_id"}, {"$ref": "#/parameters/rowFilter.orderline.name"}, {"$ref": "#/parameters/rowFilter.orderline.address"}, {"$ref": "#/parameters/rowFilter.orderline.number_of_items"}, {"$ref": "#/parameters/rowFilter.orderline.notes"}, {"$ref": "#/parameters/select"}, {"$ref": "#/parameters/order"}, {"$ref": "#/parameters/range"}, {"$ref": "#/parameters/rangeUnit"}, {"$ref": "#/parameters/offset"}, {"$ref": "#/parameters/limit"}, {"$ref": "#/parameters/preferCount"}],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {"items": {"$ref": "#/definitions/orderline"}, "type": "array"}
                    }, "206": {"description": "Partial Content"}
                },
                "summary": "Bestillinger",
                "tags": ["orderline"]
            },
            "post": {
                "parameters": [{"$ref": "#/parameters/body.orderline"}, {"$ref": "#/parameters/select"}, {"$ref": "#/parameters/preferPost"}],
                "responses": {"201": {"description": "Created"}},
                "summary": "Bestillinger",
                "tags": ["orderline"]
            },
            "delete": {
                "parameters": [{"$ref": "#/parameters/rowFilter.orderline.id"}, {"$ref": "#/parameters/rowFilter.orderline.owner_id"}, {"$ref": "#/parameters/rowFilter.orderline.name"}, {"$ref": "#/parameters/rowFilter.orderline.address"}, {"$ref": "#/parameters/rowFilter.orderline.number_of_items"}, {"$ref": "#/parameters/rowFilter.orderline.notes"}, {"$ref": "#/parameters/preferReturn"}],
                "responses": {"204": {"description": "No Content"}},
                "summary": "Bestillinger",
                "tags": ["orderline"]
            },
            "patch": {
                "parameters": [{"$ref": "#/parameters/rowFilter.orderline.id"}, {"$ref": "#/parameters/rowFilter.orderline.owner_id"}, {"$ref": "#/parameters/rowFilter.orderline.name"}, {"$ref": "#/parameters/rowFilter.orderline.address"}, {"$ref": "#/parameters/rowFilter.orderline.number_of_items"}, {"$ref": "#/parameters/rowFilter.orderline.notes"}, {"$ref": "#/parameters/body.orderline"}, {"$ref": "#/parameters/preferReturn"}],
                "responses": {"204": {"description": "No Content"}},
                "summary": "Bestillinger",
                "tags": ["orderline"]
            }
        },
        "/item": {
            "get": {
                "parameters": [{"$ref": "#/parameters/rowFilter.item.id"}, {"$ref": "#/parameters/rowFilter.item.name"}, {"$ref": "#/parameters/rowFilter.item.location"}, {"$ref": "#/parameters/select"}, {"$ref": "#/parameters/order"}, {"$ref": "#/parameters/range"}, {"$ref": "#/parameters/rangeUnit"}, {"$ref": "#/parameters/offset"}, {"$ref": "#/parameters/limit"}, {"$ref": "#/parameters/preferCount"}],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {"items": {"$ref": "#/definitions/item"}, "type": "array"}
                    }, "206": {"description": "Partial Content"}
                },
                "summary": "Gjenstand",
                "tags": ["item"]
            },
            "post": {
                "parameters": [{"$ref": "#/parameters/body.item"}, {"$ref": "#/parameters/select"}, {"$ref": "#/parameters/preferPost"}],
                "responses": {"201": {"description": "Created"}},
                "summary": "Gjenstand",
                "tags": ["item"]
            },
            "delete": {
                "parameters": [{"$ref": "#/parameters/rowFilter.item.id"}, {"$ref": "#/parameters/rowFilter.item.name"}, {"$ref": "#/parameters/rowFilter.item.location"}, {"$ref": "#/parameters/preferReturn"}],
                "responses": {"204": {"description": "No Content"}},
                "summary": "Gjenstand",
                "tags": ["item"]
            },
            "patch": {
                "parameters": [{"$ref": "#/parameters/rowFilter.item.id"}, {"$ref": "#/parameters/rowFilter.item.name"}, {"$ref": "#/parameters/rowFilter.item.location"}, {"$ref": "#/parameters/body.item"}, {"$ref": "#/parameters/preferReturn"}],
                "responses": {"204": {"description": "No Content"}},
                "summary": "Gjenstand",
                "tags": ["item"]
            }
        },
        "/lyrics": {
            "get": {
                "parameters": [{"$ref": "#/parameters/rowFilter.lyrics.id"}, {"$ref": "#/parameters/rowFilter.lyrics.has_chords"}, {"$ref": "#/parameters/rowFilter.lyrics.lyrics"}, {"$ref": "#/parameters/rowFilter.lyrics.songtitle"}, {"$ref": "#/parameters/rowFilter.lyrics.artist"}, {"$ref": "#/parameters/select"}, {"$ref": "#/parameters/order"}, {"$ref": "#/parameters/range"}, {"$ref": "#/parameters/rangeUnit"}, {"$ref": "#/parameters/offset"}, {"$ref": "#/parameters/limit"}, {"$ref": "#/parameters/preferCount"}],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {"items": {"$ref": "#/definitions/lyrics"}, "type": "array"}
                    }, "206": {"description": "Partial Content"}
                },
                "summary": "Sangtekster",
                "tags": ["lyrics"]
            },
            "post": {
                "parameters": [{"$ref": "#/parameters/body.lyrics"}, {"$ref": "#/parameters/select"}, {"$ref": "#/parameters/preferPost"}],
                "responses": {"201": {"description": "Created"}},
                "summary": "Sangtekster",
                "tags": ["lyrics"]
            },
            "delete": {
                "parameters": [{"$ref": "#/parameters/rowFilter.lyrics.id"}, {"$ref": "#/parameters/rowFilter.lyrics.has_chords"}, {"$ref": "#/parameters/rowFilter.lyrics.lyrics"}, {"$ref": "#/parameters/rowFilter.lyrics.songtitle"}, {"$ref": "#/parameters/rowFilter.lyrics.artist"}, {"$ref": "#/parameters/preferReturn"}],
                "responses": {"204": {"description": "No Content"}},
                "summary": "Sangtekster",
                "tags": ["lyrics"]
            },
            "patch": {
                "parameters": [{"$ref": "#/parameters/rowFilter.lyrics.id"}, {"$ref": "#/parameters/rowFilter.lyrics.has_chords"}, {"$ref": "#/parameters/rowFilter.lyrics.lyrics"}, {"$ref": "#/parameters/rowFilter.lyrics.songtitle"}, {"$ref": "#/parameters/rowFilter.lyrics.artist"}, {"$ref": "#/parameters/body.lyrics"}, {"$ref": "#/parameters/preferReturn"}],
                "responses": {"204": {"description": "No Content"}},
                "summary": "Sangtekster",
                "tags": ["lyrics"]
            }
        },
        "/participant_statistics": {
            "get": {
                "parameters": [{"$ref": "#/parameters/rowFilter.participant_statistics.rvsp_party"}, {"$ref": "#/parameters/rowFilter.participant_statistics.count"}, {"$ref": "#/parameters/select"}, {"$ref": "#/parameters/order"}, {"$ref": "#/parameters/range"}, {"$ref": "#/parameters/rangeUnit"}, {"$ref": "#/parameters/offset"}, {"$ref": "#/parameters/limit"}, {"$ref": "#/parameters/preferCount"}],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {"items": {"$ref": "#/definitions/participant_statistics"}, "type": "array"}
                    }, "206": {"description": "Partial Content"}
                },
                "summary": "Deltager-statistikk",
                "tags": ["participant_statistics"]
            }
        },
        "/mytable2": {
            "get": {
                "parameters": [{"$ref": "#/parameters/rowFilter.mytable2.id"}, {"$ref": "#/parameters/rowFilter.mytable2.col2"}, {"$ref": "#/parameters/rowFilter.mytable2.col3"}, {"$ref": "#/parameters/select"}, {"$ref": "#/parameters/order"}, {"$ref": "#/parameters/range"}, {"$ref": "#/parameters/rangeUnit"}, {"$ref": "#/parameters/offset"}, {"$ref": "#/parameters/limit"}, {"$ref": "#/parameters/preferCount"}],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {"items": {"$ref": "#/definitions/mytable2"}, "type": "array"}
                    }, "206": {"description": "Partial Content"}
                },
                "tags": ["mytable2"]
            },
            "post": {
                "parameters": [{"$ref": "#/parameters/body.mytable2"}, {"$ref": "#/parameters/select"}, {"$ref": "#/parameters/preferPost"}],
                "responses": {"201": {"description": "Created"}},
                "tags": ["mytable2"]
            },
            "delete": {
                "parameters": [{"$ref": "#/parameters/rowFilter.mytable2.id"}, {"$ref": "#/parameters/rowFilter.mytable2.col2"}, {"$ref": "#/parameters/rowFilter.mytable2.col3"}, {"$ref": "#/parameters/preferReturn"}],
                "responses": {"204": {"description": "No Content"}},
                "tags": ["mytable2"]
            },
            "patch": {
                "parameters": [{"$ref": "#/parameters/rowFilter.mytable2.id"}, {"$ref": "#/parameters/rowFilter.mytable2.col2"}, {"$ref": "#/parameters/rowFilter.mytable2.col3"}, {"$ref": "#/parameters/body.mytable2"}, {"$ref": "#/parameters/preferReturn"}],
                "responses": {"204": {"description": "No Content"}},
                "tags": ["mytable2"]
            }
        },
        "/employment": {
            "get": {
                "parameters": [{"$ref": "#/parameters/rowFilter.employment.id"}, {"$ref": "#/parameters/rowFilter.employment.teacher_id"}, {"$ref": "#/parameters/rowFilter.employment.school_id"}, {"$ref": "#/parameters/select"}, {"$ref": "#/parameters/order"}, {"$ref": "#/parameters/range"}, {"$ref": "#/parameters/rangeUnit"}, {"$ref": "#/parameters/offset"}, {"$ref": "#/parameters/limit"}, {"$ref": "#/parameters/preferCount"}],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {"items": {"$ref": "#/definitions/employment"}, "type": "array"}
                    }, "206": {"description": "Partial Content"}
                },
                "summary": "Ansettelse",
                "tags": ["employment"]
            },
            "post": {
                "parameters": [{"$ref": "#/parameters/body.employment"}, {"$ref": "#/parameters/select"}, {"$ref": "#/parameters/preferPost"}],
                "responses": {"201": {"description": "Created"}},
                "summary": "Ansettelse",
                "tags": ["employment"]
            },
            "delete": {
                "parameters": [{"$ref": "#/parameters/rowFilter.employment.id"}, {"$ref": "#/parameters/rowFilter.employment.teacher_id"}, {"$ref": "#/parameters/rowFilter.employment.school_id"}, {"$ref": "#/parameters/preferReturn"}],
                "responses": {"204": {"description": "No Content"}},
                "summary": "Ansettelse",
                "tags": ["employment"]
            },
            "patch": {
                "parameters": [{"$ref": "#/parameters/rowFilter.employment.id"}, {"$ref": "#/parameters/rowFilter.employment.teacher_id"}, {"$ref": "#/parameters/rowFilter.employment.school_id"}, {"$ref": "#/parameters/body.employment"}, {"$ref": "#/parameters/preferReturn"}],
                "responses": {"204": {"description": "No Content"}},
                "summary": "Ansettelse",
                "tags": ["employment"]
            }
        },
        "/school": {
            "get": {
                "parameters": [{"$ref": "#/parameters/rowFilter.school.id"}, {"$ref": "#/parameters/rowFilter.school.name"}, {"$ref": "#/parameters/select"}, {"$ref": "#/parameters/order"}, {"$ref": "#/parameters/range"}, {"$ref": "#/parameters/rangeUnit"}, {"$ref": "#/parameters/offset"}, {"$ref": "#/parameters/limit"}, {"$ref": "#/parameters/preferCount"}],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {"items": {"$ref": "#/definitions/school"}, "type": "array"}
                    }, "206": {"description": "Partial Content"}
                },
                "summary": "Skoler",
                "tags": ["school"]
            },
            "post": {
                "parameters": [{"$ref": "#/parameters/body.school"}, {"$ref": "#/parameters/select"}, {"$ref": "#/parameters/preferPost"}],
                "responses": {"201": {"description": "Created"}},
                "summary": "Skoler",
                "tags": ["school"]
            },
            "delete": {
                "parameters": [{"$ref": "#/parameters/rowFilter.school.id"}, {"$ref": "#/parameters/rowFilter.school.name"}, {"$ref": "#/parameters/preferReturn"}],
                "responses": {"204": {"description": "No Content"}},
                "summary": "Skoler",
                "tags": ["school"]
            },
            "patch": {
                "parameters": [{"$ref": "#/parameters/rowFilter.school.id"}, {"$ref": "#/parameters/rowFilter.school.name"}, {"$ref": "#/parameters/body.school"}, {"$ref": "#/parameters/preferReturn"}],
                "responses": {"204": {"description": "No Content"}},
                "summary": "Skoler",
                "tags": ["school"]
            }
        },
        "/answer": {
            "get": {
                "parameters": [{"$ref": "#/parameters/rowFilter.answer.id"}, {"$ref": "#/parameters/rowFilter.answer.student_id"}, {"$ref": "#/parameters/rowFilter.answer.question_id"}, {"$ref": "#/parameters/rowFilter.answer.points"}, {"$ref": "#/parameters/rowFilter.answer.comments"}, {"$ref": "#/parameters/rowFilter.answer.questionnaire_id"}, {"$ref": "#/parameters/select"}, {"$ref": "#/parameters/order"}, {"$ref": "#/parameters/range"}, {"$ref": "#/parameters/rangeUnit"}, {"$ref": "#/parameters/offset"}, {"$ref": "#/parameters/limit"}, {"$ref": "#/parameters/preferCount"}],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {"items": {"$ref": "#/definitions/answer"}, "type": "array"}
                    }, "206": {"description": "Partial Content"}
                },
                "summary": "Besvarelse",
                "tags": ["answer"]
            },
            "post": {
                "parameters": [{"$ref": "#/parameters/body.answer"}, {"$ref": "#/parameters/select"}, {"$ref": "#/parameters/preferPost"}],
                "responses": {"201": {"description": "Created"}},
                "summary": "Besvarelse",
                "tags": ["answer"]
            },
            "delete": {
                "parameters": [{"$ref": "#/parameters/rowFilter.answer.id"}, {"$ref": "#/parameters/rowFilter.answer.student_id"}, {"$ref": "#/parameters/rowFilter.answer.question_id"}, {"$ref": "#/parameters/rowFilter.answer.points"}, {"$ref": "#/parameters/rowFilter.answer.comments"}, {"$ref": "#/parameters/rowFilter.answer.questionnaire_id"}, {"$ref": "#/parameters/preferReturn"}],
                "responses": {"204": {"description": "No Content"}},
                "summary": "Besvarelse",
                "tags": ["answer"]
            },
            "patch": {
                "parameters": [{"$ref": "#/parameters/rowFilter.answer.id"}, {"$ref": "#/parameters/rowFilter.answer.student_id"}, {"$ref": "#/parameters/rowFilter.answer.question_id"}, {"$ref": "#/parameters/rowFilter.answer.points"}, {"$ref": "#/parameters/rowFilter.answer.comments"}, {"$ref": "#/parameters/rowFilter.answer.questionnaire_id"}, {"$ref": "#/parameters/body.answer"}, {"$ref": "#/parameters/preferReturn"}],
                "responses": {"204": {"description": "No Content"}},
                "summary": "Besvarelse",
                "tags": ["answer"]
            }
        },
        "/teacher": {
            "get": {
                "parameters": [{"$ref": "#/parameters/rowFilter.teacher.id"}, {"$ref": "#/parameters/rowFilter.teacher.course_id"}, {"$ref": "#/parameters/rowFilter.teacher.teacher_id"}, {"$ref": "#/parameters/select"}, {"$ref": "#/parameters/order"}, {"$ref": "#/parameters/range"}, {"$ref": "#/parameters/rangeUnit"}, {"$ref": "#/parameters/offset"}, {"$ref": "#/parameters/limit"}, {"$ref": "#/parameters/preferCount"}],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {"items": {"$ref": "#/definitions/teacher"}, "type": "array"}
                    }, "206": {"description": "Partial Content"}
                },
                "summary": "Lærer",
                "tags": ["teacher"]
            },
            "post": {
                "parameters": [{"$ref": "#/parameters/body.teacher"}, {"$ref": "#/parameters/select"}, {"$ref": "#/parameters/preferPost"}],
                "responses": {"201": {"description": "Created"}},
                "summary": "Lærer",
                "tags": ["teacher"]
            },
            "delete": {
                "parameters": [{"$ref": "#/parameters/rowFilter.teacher.id"}, {"$ref": "#/parameters/rowFilter.teacher.course_id"}, {"$ref": "#/parameters/rowFilter.teacher.teacher_id"}, {"$ref": "#/parameters/preferReturn"}],
                "responses": {"204": {"description": "No Content"}},
                "summary": "Lærer",
                "tags": ["teacher"]
            },
            "patch": {
                "parameters": [{"$ref": "#/parameters/rowFilter.teacher.id"}, {"$ref": "#/parameters/rowFilter.teacher.course_id"}, {"$ref": "#/parameters/rowFilter.teacher.teacher_id"}, {"$ref": "#/parameters/body.teacher"}, {"$ref": "#/parameters/preferReturn"}],
                "responses": {"204": {"description": "No Content"}},
                "summary": "Lærer",
                "tags": ["teacher"]
            }
        },
        "/student": {
            "get": {
                "parameters": [{"$ref": "#/parameters/rowFilter.student.id"}, {"$ref": "#/parameters/rowFilter.student.name"}, {"$ref": "#/parameters/rowFilter.student.comments"}, {"$ref": "#/parameters/rowFilter.student.owner_id"}, {"$ref": "#/parameters/select"}, {"$ref": "#/parameters/order"}, {"$ref": "#/parameters/range"}, {"$ref": "#/parameters/rangeUnit"}, {"$ref": "#/parameters/offset"}, {"$ref": "#/parameters/limit"}, {"$ref": "#/parameters/preferCount"}],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {"items": {"$ref": "#/definitions/student"}, "type": "array"}
                    }, "206": {"description": "Partial Content"}
                },
                "summary": "Elever",
                "tags": ["student"]
            },
            "post": {
                "parameters": [{"$ref": "#/parameters/body.student"}, {"$ref": "#/parameters/select"}, {"$ref": "#/parameters/preferPost"}],
                "responses": {"201": {"description": "Created"}},
                "summary": "Elever",
                "tags": ["student"]
            },
            "delete": {
                "parameters": [{"$ref": "#/parameters/rowFilter.student.id"}, {"$ref": "#/parameters/rowFilter.student.name"}, {"$ref": "#/parameters/rowFilter.student.comments"}, {"$ref": "#/parameters/rowFilter.student.owner_id"}, {"$ref": "#/parameters/preferReturn"}],
                "responses": {"204": {"description": "No Content"}},
                "summary": "Elever",
                "tags": ["student"]
            },
            "patch": {
                "parameters": [{"$ref": "#/parameters/rowFilter.student.id"}, {"$ref": "#/parameters/rowFilter.student.name"}, {"$ref": "#/parameters/rowFilter.student.comments"}, {"$ref": "#/parameters/rowFilter.student.owner_id"}, {"$ref": "#/parameters/body.student"}, {"$ref": "#/parameters/preferReturn"}],
                "responses": {"204": {"description": "No Content"}},
                "summary": "Elever",
                "tags": ["student"]
            }
        },
        "/ceremony_statistics": {
            "get": {
                "parameters": [{"$ref": "#/parameters/rowFilter.ceremony_statistics.rvsp_ceremony"}, {"$ref": "#/parameters/rowFilter.ceremony_statistics.count"}, {"$ref": "#/parameters/select"}, {"$ref": "#/parameters/order"}, {"$ref": "#/parameters/range"}, {"$ref": "#/parameters/rangeUnit"}, {"$ref": "#/parameters/offset"}, {"$ref": "#/parameters/limit"}, {"$ref": "#/parameters/preferCount"}],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {"items": {"$ref": "#/definitions/ceremony_statistics"}, "type": "array"}
                    }, "206": {"description": "Partial Content"}
                },
                "summary": "Deltager-statistikk",
                "tags": ["ceremony_statistics"]
            }
        },
        "/course": {
            "get": {
                "parameters": [{"$ref": "#/parameters/rowFilter.course.id"}, {"$ref": "#/parameters/rowFilter.course.school_id"}, {"$ref": "#/parameters/rowFilter.course.name"}, {"$ref": "#/parameters/select"}, {"$ref": "#/parameters/order"}, {"$ref": "#/parameters/range"}, {"$ref": "#/parameters/rangeUnit"}, {"$ref": "#/parameters/offset"}, {"$ref": "#/parameters/limit"}, {"$ref": "#/parameters/preferCount"}],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {"items": {"$ref": "#/definitions/course"}, "type": "array"}
                    }, "206": {"description": "Partial Content"}
                },
                "summary": "Kurs",
                "tags": ["course"]
            },
            "post": {
                "parameters": [{"$ref": "#/parameters/body.course"}, {"$ref": "#/parameters/select"}, {"$ref": "#/parameters/preferPost"}],
                "responses": {"201": {"description": "Created"}},
                "summary": "Kurs",
                "tags": ["course"]
            },
            "delete": {
                "parameters": [{"$ref": "#/parameters/rowFilter.course.id"}, {"$ref": "#/parameters/rowFilter.course.school_id"}, {"$ref": "#/parameters/rowFilter.course.name"}, {"$ref": "#/parameters/preferReturn"}],
                "responses": {"204": {"description": "No Content"}},
                "summary": "Kurs",
                "tags": ["course"]
            },
            "patch": {
                "parameters": [{"$ref": "#/parameters/rowFilter.course.id"}, {"$ref": "#/parameters/rowFilter.course.school_id"}, {"$ref": "#/parameters/rowFilter.course.name"}, {"$ref": "#/parameters/body.course"}, {"$ref": "#/parameters/preferReturn"}],
                "responses": {"204": {"description": "No Content"}},
                "summary": "Kurs",
                "tags": ["course"]
            }
        },
        "/user": {
            "get": {
                "parameters": [{"$ref": "#/parameters/rowFilter.user.id"}, {"$ref": "#/parameters/rowFilter.user.email"}, {"$ref": "#/parameters/rowFilter.user.role"}, {"$ref": "#/parameters/select"}, {"$ref": "#/parameters/order"}, {"$ref": "#/parameters/range"}, {"$ref": "#/parameters/rangeUnit"}, {"$ref": "#/parameters/offset"}, {"$ref": "#/parameters/limit"}, {"$ref": "#/parameters/preferCount"}],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {"items": {"$ref": "#/definitions/user"}, "type": "array"}
                    }, "206": {"description": "Partial Content"}
                },
                "tags": ["user"]
            },
            "post": {
                "parameters": [{"$ref": "#/parameters/body.user"}, {"$ref": "#/parameters/select"}, {"$ref": "#/parameters/preferPost"}],
                "responses": {"201": {"description": "Created"}},
                "tags": ["user"]
            },
            "delete": {
                "parameters": [{"$ref": "#/parameters/rowFilter.user.id"}, {"$ref": "#/parameters/rowFilter.user.email"}, {"$ref": "#/parameters/rowFilter.user.role"}, {"$ref": "#/parameters/preferReturn"}],
                "responses": {"204": {"description": "No Content"}},
                "tags": ["user"]
            },
            "patch": {
                "parameters": [{"$ref": "#/parameters/rowFilter.user.id"}, {"$ref": "#/parameters/rowFilter.user.email"}, {"$ref": "#/parameters/rowFilter.user.role"}, {"$ref": "#/parameters/body.user"}, {"$ref": "#/parameters/preferReturn"}],
                "responses": {"204": {"description": "No Content"}},
                "tags": ["user"]
            }
        },
        "/assignment": {
            "get": {
                "parameters": [{"$ref": "#/parameters/rowFilter.assignment.id"}, {"$ref": "#/parameters/rowFilter.assignment.enrollment_id"}, {"$ref": "#/parameters/rowFilter.assignment.status"}, {"$ref": "#/parameters/rowFilter.assignment.title"}, {"$ref": "#/parameters/rowFilter.assignment.description"}, {"$ref": "#/parameters/rowFilter.assignment.attachment"}, {"$ref": "#/parameters/select"}, {"$ref": "#/parameters/order"}, {"$ref": "#/parameters/range"}, {"$ref": "#/parameters/rangeUnit"}, {"$ref": "#/parameters/offset"}, {"$ref": "#/parameters/limit"}, {"$ref": "#/parameters/preferCount"}],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {"items": {"$ref": "#/definitions/assignment"}, "type": "array"}
                    }, "206": {"description": "Partial Content"}
                },
                "summary": "Lekser",
                "tags": ["assignment"]
            },
            "post": {
                "parameters": [{"$ref": "#/parameters/body.assignment"}, {"$ref": "#/parameters/select"}, {"$ref": "#/parameters/preferPost"}],
                "responses": {"201": {"description": "Created"}},
                "summary": "Lekser",
                "tags": ["assignment"]
            },
            "delete": {
                "parameters": [{"$ref": "#/parameters/rowFilter.assignment.id"}, {"$ref": "#/parameters/rowFilter.assignment.enrollment_id"}, {"$ref": "#/parameters/rowFilter.assignment.status"}, {"$ref": "#/parameters/rowFilter.assignment.title"}, {"$ref": "#/parameters/rowFilter.assignment.description"}, {"$ref": "#/parameters/rowFilter.assignment.attachment"}, {"$ref": "#/parameters/preferReturn"}],
                "responses": {"204": {"description": "No Content"}},
                "summary": "Lekser",
                "tags": ["assignment"]
            },
            "patch": {
                "parameters": [{"$ref": "#/parameters/rowFilter.assignment.id"}, {"$ref": "#/parameters/rowFilter.assignment.enrollment_id"}, {"$ref": "#/parameters/rowFilter.assignment.status"}, {"$ref": "#/parameters/rowFilter.assignment.title"}, {"$ref": "#/parameters/rowFilter.assignment.description"}, {"$ref": "#/parameters/rowFilter.assignment.attachment"}, {"$ref": "#/parameters/body.assignment"}, {"$ref": "#/parameters/preferReturn"}],
                "responses": {"204": {"description": "No Content"}},
                "summary": "Lekser",
                "tags": ["assignment"]
            }
        },
        "/questionnaire": {
            "get": {
                "parameters": [{"$ref": "#/parameters/rowFilter.questionnaire.id"}, {"$ref": "#/parameters/rowFilter.questionnaire.name"}, {"$ref": "#/parameters/rowFilter.questionnaire.owner_id"}, {"$ref": "#/parameters/select"}, {"$ref": "#/parameters/order"}, {"$ref": "#/parameters/range"}, {"$ref": "#/parameters/rangeUnit"}, {"$ref": "#/parameters/offset"}, {"$ref": "#/parameters/limit"}, {"$ref": "#/parameters/preferCount"}],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {"items": {"$ref": "#/definitions/questionnaire"}, "type": "array"}
                    }, "206": {"description": "Partial Content"}
                },
                "summary": "Prøver",
                "tags": ["questionnaire"]
            },
            "post": {
                "parameters": [{"$ref": "#/parameters/body.questionnaire"}, {"$ref": "#/parameters/select"}, {"$ref": "#/parameters/preferPost"}],
                "responses": {"201": {"description": "Created"}},
                "summary": "Prøver",
                "tags": ["questionnaire"]
            },
            "delete": {
                "parameters": [{"$ref": "#/parameters/rowFilter.questionnaire.id"}, {"$ref": "#/parameters/rowFilter.questionnaire.name"}, {"$ref": "#/parameters/rowFilter.questionnaire.owner_id"}, {"$ref": "#/parameters/preferReturn"}],
                "responses": {"204": {"description": "No Content"}},
                "summary": "Prøver",
                "tags": ["questionnaire"]
            },
            "patch": {
                "parameters": [{"$ref": "#/parameters/rowFilter.questionnaire.id"}, {"$ref": "#/parameters/rowFilter.questionnaire.name"}, {"$ref": "#/parameters/rowFilter.questionnaire.owner_id"}, {"$ref": "#/parameters/body.questionnaire"}, {"$ref": "#/parameters/preferReturn"}],
                "responses": {"204": {"description": "No Content"}},
                "summary": "Prøver",
                "tags": ["questionnaire"]
            }
        },
        "/profiles": {
            "get": {
                "parameters": [{"$ref": "#/parameters/rowFilter.profiles.id"}, {"$ref": "#/parameters/rowFilter.profiles.updated_at"}, {"$ref": "#/parameters/rowFilter.profiles.username"}, {"$ref": "#/parameters/rowFilter.profiles.avatar_url"}, {"$ref": "#/parameters/rowFilter.profiles.website"}, {"$ref": "#/parameters/select"}, {"$ref": "#/parameters/order"}, {"$ref": "#/parameters/range"}, {"$ref": "#/parameters/rangeUnit"}, {"$ref": "#/parameters/offset"}, {"$ref": "#/parameters/limit"}, {"$ref": "#/parameters/preferCount"}],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {"items": {"$ref": "#/definitions/profiles"}, "type": "array"}
                    }, "206": {"description": "Partial Content"}
                },
                "summary": "Brukerprofiler",
                "tags": ["profiles"]
            },
            "post": {
                "parameters": [{"$ref": "#/parameters/body.profiles"}, {"$ref": "#/parameters/select"}, {"$ref": "#/parameters/preferPost"}],
                "responses": {"201": {"description": "Created"}},
                "summary": "Brukerprofiler",
                "tags": ["profiles"]
            },
            "delete": {
                "parameters": [{"$ref": "#/parameters/rowFilter.profiles.id"}, {"$ref": "#/parameters/rowFilter.profiles.updated_at"}, {"$ref": "#/parameters/rowFilter.profiles.username"}, {"$ref": "#/parameters/rowFilter.profiles.avatar_url"}, {"$ref": "#/parameters/rowFilter.profiles.website"}, {"$ref": "#/parameters/preferReturn"}],
                "responses": {"204": {"description": "No Content"}},
                "summary": "Brukerprofiler",
                "tags": ["profiles"]
            },
            "patch": {
                "parameters": [{"$ref": "#/parameters/rowFilter.profiles.id"}, {"$ref": "#/parameters/rowFilter.profiles.updated_at"}, {"$ref": "#/parameters/rowFilter.profiles.username"}, {"$ref": "#/parameters/rowFilter.profiles.avatar_url"}, {"$ref": "#/parameters/rowFilter.profiles.website"}, {"$ref": "#/parameters/body.profiles"}, {"$ref": "#/parameters/preferReturn"}],
                "responses": {"204": {"description": "No Content"}},
                "summary": "Brukerprofiler",
                "tags": ["profiles"]
            }
        },
        "/question": {
            "get": {
                "parameters": [{"$ref": "#/parameters/rowFilter.question.id"}, {"$ref": "#/parameters/rowFilter.question.name"}, {"$ref": "#/parameters/rowFilter.question.comments"}, {"$ref": "#/parameters/rowFilter.question.points"}, {"$ref": "#/parameters/rowFilter.question.questionnaire_id"}, {"$ref": "#/parameters/select"}, {"$ref": "#/parameters/order"}, {"$ref": "#/parameters/range"}, {"$ref": "#/parameters/rangeUnit"}, {"$ref": "#/parameters/offset"}, {"$ref": "#/parameters/limit"}, {"$ref": "#/parameters/preferCount"}],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {"items": {"$ref": "#/definitions/question"}, "type": "array"}
                    }, "206": {"description": "Partial Content"}
                },
                "summary": "Spørsmål",
                "tags": ["question"]
            },
            "post": {
                "parameters": [{"$ref": "#/parameters/body.question"}, {"$ref": "#/parameters/select"}, {"$ref": "#/parameters/preferPost"}],
                "responses": {"201": {"description": "Created"}},
                "summary": "Spørsmål",
                "tags": ["question"]
            },
            "delete": {
                "parameters": [{"$ref": "#/parameters/rowFilter.question.id"}, {"$ref": "#/parameters/rowFilter.question.name"}, {"$ref": "#/parameters/rowFilter.question.comments"}, {"$ref": "#/parameters/rowFilter.question.points"}, {"$ref": "#/parameters/rowFilter.question.questionnaire_id"}, {"$ref": "#/parameters/preferReturn"}],
                "responses": {"204": {"description": "No Content"}},
                "summary": "Spørsmål",
                "tags": ["question"]
            },
            "patch": {
                "parameters": [{"$ref": "#/parameters/rowFilter.question.id"}, {"$ref": "#/parameters/rowFilter.question.name"}, {"$ref": "#/parameters/rowFilter.question.comments"}, {"$ref": "#/parameters/rowFilter.question.points"}, {"$ref": "#/parameters/rowFilter.question.questionnaire_id"}, {"$ref": "#/parameters/body.question"}, {"$ref": "#/parameters/preferReturn"}],
                "responses": {"204": {"description": "No Content"}},
                "summary": "Spørsmål",
                "tags": ["question"]
            }
        },
        "/participant": {
            "get": {
                "parameters": [{"$ref": "#/parameters/rowFilter.participant.id"}, {"$ref": "#/parameters/rowFilter.participant.name"}, {"$ref": "#/parameters/rowFilter.participant.email"}, {"$ref": "#/parameters/rowFilter.participant.description"}, {"$ref": "#/parameters/rowFilter.participant.tasks"}, {"$ref": "#/parameters/rowFilter.participant.rvsp_ceremony"}, {"$ref": "#/parameters/rowFilter.participant.sort_order"}, {"$ref": "#/parameters/rowFilter.participant.rvsp_party"}, {"$ref": "#/parameters/rowFilter.participant.phone_number"}, {"$ref": "#/parameters/select"}, {"$ref": "#/parameters/order"}, {"$ref": "#/parameters/range"}, {"$ref": "#/parameters/rangeUnit"}, {"$ref": "#/parameters/offset"}, {"$ref": "#/parameters/limit"}, {"$ref": "#/parameters/preferCount"}],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {"items": {"$ref": "#/definitions/participant"}, "type": "array"}
                    }, "206": {"description": "Partial Content"}
                },
                "summary": "Deltagere",
                "tags": ["participant"]
            },
            "post": {
                "parameters": [{"$ref": "#/parameters/body.participant"}, {"$ref": "#/parameters/select"}, {"$ref": "#/parameters/preferPost"}],
                "responses": {"201": {"description": "Created"}},
                "summary": "Deltagere",
                "tags": ["participant"]
            },
            "delete": {
                "parameters": [{"$ref": "#/parameters/rowFilter.participant.id"}, {"$ref": "#/parameters/rowFilter.participant.name"}, {"$ref": "#/parameters/rowFilter.participant.email"}, {"$ref": "#/parameters/rowFilter.participant.description"}, {"$ref": "#/parameters/rowFilter.participant.tasks"}, {"$ref": "#/parameters/rowFilter.participant.rvsp_ceremony"}, {"$ref": "#/parameters/rowFilter.participant.sort_order"}, {"$ref": "#/parameters/rowFilter.participant.rvsp_party"}, {"$ref": "#/parameters/rowFilter.participant.phone_number"}, {"$ref": "#/parameters/preferReturn"}],
                "responses": {"204": {"description": "No Content"}},
                "summary": "Deltagere",
                "tags": ["participant"]
            },
            "patch": {
                "parameters": [{"$ref": "#/parameters/rowFilter.participant.id"}, {"$ref": "#/parameters/rowFilter.participant.name"}, {"$ref": "#/parameters/rowFilter.participant.email"}, {"$ref": "#/parameters/rowFilter.participant.description"}, {"$ref": "#/parameters/rowFilter.participant.tasks"}, {"$ref": "#/parameters/rowFilter.participant.rvsp_ceremony"}, {"$ref": "#/parameters/rowFilter.participant.sort_order"}, {"$ref": "#/parameters/rowFilter.participant.rvsp_party"}, {"$ref": "#/parameters/rowFilter.participant.phone_number"}, {"$ref": "#/parameters/body.participant"}, {"$ref": "#/parameters/preferReturn"}],
                "responses": {"204": {"description": "No Content"}},
                "summary": "Deltagere",
                "tags": ["participant"]
            }
        },
        "/orderline_statistics": {
            "get": {
                "parameters": [{"$ref": "#/parameters/rowFilter.orderline_statistics.label"}, {"$ref": "#/parameters/rowFilter.orderline_statistics.number_of_items"}, {"$ref": "#/parameters/rowFilter.orderline_statistics.unit"}, {"$ref": "#/parameters/rowFilter.orderline_statistics.amount_pr_item"}, {"$ref": "#/parameters/rowFilter.orderline_statistics.total_amount"}, {"$ref": "#/parameters/select"}, {"$ref": "#/parameters/order"}, {"$ref": "#/parameters/range"}, {"$ref": "#/parameters/rangeUnit"}, {"$ref": "#/parameters/offset"}, {"$ref": "#/parameters/limit"}, {"$ref": "#/parameters/preferCount"}],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {"items": {"$ref": "#/definitions/orderline_statistics"}, "type": "array"}
                    }, "206": {"description": "Partial Content"}
                },
                "summary": "Bestillingsstatistikk",
                "tags": ["orderline_statistics"]
            }
        },
        "/mytable": {
            "get": {
                "parameters": [{"$ref": "#/parameters/rowFilter.mytable.id"}, {"$ref": "#/parameters/rowFilter.mytable.task"}, {"$ref": "#/parameters/rowFilter.mytable.is_done"}, {"$ref": "#/parameters/select"}, {"$ref": "#/parameters/order"}, {"$ref": "#/parameters/range"}, {"$ref": "#/parameters/rangeUnit"}, {"$ref": "#/parameters/offset"}, {"$ref": "#/parameters/limit"}, {"$ref": "#/parameters/preferCount"}],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {"items": {"$ref": "#/definitions/mytable"}, "type": "array"}
                    }, "206": {"description": "Partial Content"}
                },
                "tags": ["mytable"]
            },
            "post": {
                "parameters": [{"$ref": "#/parameters/body.mytable"}, {"$ref": "#/parameters/select"}, {"$ref": "#/parameters/preferPost"}],
                "responses": {"201": {"description": "Created"}},
                "tags": ["mytable"]
            },
            "delete": {
                "parameters": [{"$ref": "#/parameters/rowFilter.mytable.id"}, {"$ref": "#/parameters/rowFilter.mytable.task"}, {"$ref": "#/parameters/rowFilter.mytable.is_done"}, {"$ref": "#/parameters/preferReturn"}],
                "responses": {"204": {"description": "No Content"}},
                "tags": ["mytable"]
            },
            "patch": {
                "parameters": [{"$ref": "#/parameters/rowFilter.mytable.id"}, {"$ref": "#/parameters/rowFilter.mytable.task"}, {"$ref": "#/parameters/rowFilter.mytable.is_done"}, {"$ref": "#/parameters/body.mytable"}, {"$ref": "#/parameters/preferReturn"}],
                "responses": {"204": {"description": "No Content"}},
                "tags": ["mytable"]
            }
        },
        "/enrollment": {
            "get": {
                "parameters": [{"$ref": "#/parameters/rowFilter.enrollment.id"}, {"$ref": "#/parameters/rowFilter.enrollment.student_id"}, {"$ref": "#/parameters/rowFilter.enrollment.course_id"}, {"$ref": "#/parameters/select"}, {"$ref": "#/parameters/order"}, {"$ref": "#/parameters/range"}, {"$ref": "#/parameters/rangeUnit"}, {"$ref": "#/parameters/offset"}, {"$ref": "#/parameters/limit"}, {"$ref": "#/parameters/preferCount"}],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {"items": {"$ref": "#/definitions/enrollment"}, "type": "array"}
                    }, "206": {"description": "Partial Content"}
                },
                "summary": "Deltagelse",
                "tags": ["enrollment"]
            },
            "post": {
                "parameters": [{"$ref": "#/parameters/body.enrollment"}, {"$ref": "#/parameters/select"}, {"$ref": "#/parameters/preferPost"}],
                "responses": {"201": {"description": "Created"}},
                "summary": "Deltagelse",
                "tags": ["enrollment"]
            },
            "delete": {
                "parameters": [{"$ref": "#/parameters/rowFilter.enrollment.id"}, {"$ref": "#/parameters/rowFilter.enrollment.student_id"}, {"$ref": "#/parameters/rowFilter.enrollment.course_id"}, {"$ref": "#/parameters/preferReturn"}],
                "responses": {"204": {"description": "No Content"}},
                "summary": "Deltagelse",
                "tags": ["enrollment"]
            },
            "patch": {
                "parameters": [{"$ref": "#/parameters/rowFilter.enrollment.id"}, {"$ref": "#/parameters/rowFilter.enrollment.student_id"}, {"$ref": "#/parameters/rowFilter.enrollment.course_id"}, {"$ref": "#/parameters/body.enrollment"}, {"$ref": "#/parameters/preferReturn"}],
                "responses": {"204": {"description": "No Content"}},
                "summary": "Deltagelse",
                "tags": ["enrollment"]
            }
        },
        "/location": {
            "get": {
                "parameters": [{"$ref": "#/parameters/rowFilter.location.id"}, {"$ref": "#/parameters/rowFilter.location.name"}, {"$ref": "#/parameters/select"}, {"$ref": "#/parameters/order"}, {"$ref": "#/parameters/range"}, {"$ref": "#/parameters/rangeUnit"}, {"$ref": "#/parameters/offset"}, {"$ref": "#/parameters/limit"}, {"$ref": "#/parameters/preferCount"}],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {"items": {"$ref": "#/definitions/location"}, "type": "array"}
                    }, "206": {"description": "Partial Content"}
                },
                "summary": "Lokasjoner",
                "tags": ["location"]
            },
            "post": {
                "parameters": [{"$ref": "#/parameters/body.location"}, {"$ref": "#/parameters/select"}, {"$ref": "#/parameters/preferPost"}],
                "responses": {"201": {"description": "Created"}},
                "summary": "Lokasjoner",
                "tags": ["location"]
            },
            "delete": {
                "parameters": [{"$ref": "#/parameters/rowFilter.location.id"}, {"$ref": "#/parameters/rowFilter.location.name"}, {"$ref": "#/parameters/preferReturn"}],
                "responses": {"204": {"description": "No Content"}},
                "summary": "Lokasjoner",
                "tags": ["location"]
            },
            "patch": {
                "parameters": [{"$ref": "#/parameters/rowFilter.location.id"}, {"$ref": "#/parameters/rowFilter.location.name"}, {"$ref": "#/parameters/body.location"}, {"$ref": "#/parameters/preferReturn"}],
                "responses": {"204": {"description": "No Content"}},
                "summary": "Lokasjoner",
                "tags": ["location"]
            }
        },
        "/countries": {
            "get": {
                "parameters": [{"$ref": "#/parameters/rowFilter.countries.id"}, {"$ref": "#/parameters/rowFilter.countries.name"}, {"$ref": "#/parameters/rowFilter.countries.iso2"}, {"$ref": "#/parameters/rowFilter.countries.iso3"}, {"$ref": "#/parameters/rowFilter.countries.local_name"}, {"$ref": "#/parameters/rowFilter.countries.continent"}, {"$ref": "#/parameters/select"}, {"$ref": "#/parameters/order"}, {"$ref": "#/parameters/range"}, {"$ref": "#/parameters/rangeUnit"}, {"$ref": "#/parameters/offset"}, {"$ref": "#/parameters/limit"}, {"$ref": "#/parameters/preferCount"}],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {"items": {"$ref": "#/definitions/countries"}, "type": "array"}
                    }, "206": {"description": "Partial Content"}
                },
                "summary": "Full list of countries.",
                "tags": ["countries"]
            },
            "post": {
                "parameters": [{"$ref": "#/parameters/body.countries"}, {"$ref": "#/parameters/select"}, {"$ref": "#/parameters/preferPost"}],
                "responses": {"201": {"description": "Created"}},
                "summary": "Full list of countries.",
                "tags": ["countries"]
            },
            "delete": {
                "parameters": [{"$ref": "#/parameters/rowFilter.countries.id"}, {"$ref": "#/parameters/rowFilter.countries.name"}, {"$ref": "#/parameters/rowFilter.countries.iso2"}, {"$ref": "#/parameters/rowFilter.countries.iso3"}, {"$ref": "#/parameters/rowFilter.countries.local_name"}, {"$ref": "#/parameters/rowFilter.countries.continent"}, {"$ref": "#/parameters/preferReturn"}],
                "responses": {"204": {"description": "No Content"}},
                "summary": "Full list of countries.",
                "tags": ["countries"]
            },
            "patch": {
                "parameters": [{"$ref": "#/parameters/rowFilter.countries.id"}, {"$ref": "#/parameters/rowFilter.countries.name"}, {"$ref": "#/parameters/rowFilter.countries.iso2"}, {"$ref": "#/parameters/rowFilter.countries.iso3"}, {"$ref": "#/parameters/rowFilter.countries.local_name"}, {"$ref": "#/parameters/rowFilter.countries.continent"}, {"$ref": "#/parameters/body.countries"}, {"$ref": "#/parameters/preferReturn"}],
                "responses": {"204": {"description": "No Content"}},
                "summary": "Full list of countries.",
                "tags": ["countries"]
            }
        },
        "/rpc/f": {
            "get": {
                "produces": ["application/json", "application/vnd.pgrst.object+json;nulls=stripped", "application/vnd.pgrst.object+json"],
                "responses": {"200": {"description": "OK"}},
                "tags": ["(rpc) f"]
            },
            "post": {
                "parameters": [{
                    "in": "body",
                    "name": "args",
                    "required": true,
                    "schema": {"type": "object"}
                }, {"$ref": "#/parameters/preferParams"}],
                "produces": ["application/json", "application/vnd.pgrst.object+json;nulls=stripped", "application/vnd.pgrst.object+json"],
                "responses": {"200": {"description": "OK"}},
                "tags": ["(rpc) f"]
            }
        },
        "/rpc/rowset_to_header": {
            "get": {
                "parameters": [{
                    "format": "anyarray",
                    "in": "query",
                    "name": "the_rows",
                    "required": true,
                    "type": "string"
                }],
                "produces": ["application/json", "application/vnd.pgrst.object+json;nulls=stripped", "application/vnd.pgrst.object+json"],
                "responses": {"200": {"description": "OK"}},
                "tags": ["(rpc) rowset_to_header"]
            },
            "post": {
                "parameters": [{
                    "in": "body",
                    "name": "args",
                    "required": true,
                    "schema": {
                        "properties": {"the_rows": {"format": "anyarray", "type": "string"}},
                        "required": ["the_rows"],
                        "type": "object"
                    }
                }, {"$ref": "#/parameters/preferParams"}],
                "produces": ["application/json", "application/vnd.pgrst.object+json;nulls=stripped", "application/vnd.pgrst.object+json"],
                "responses": {"200": {"description": "OK"}},
                "tags": ["(rpc) rowset_to_header"]
            }
        },
        "/rpc/canmodify": {
            "get": {
                "parameters": [{
                    "format": "text",
                    "in": "query",
                    "name": "",
                    "required": true,
                    "type": "string"
                }],
                "produces": ["application/json", "application/vnd.pgrst.object+json;nulls=stripped", "application/vnd.pgrst.object+json"],
                "responses": {"200": {"description": "OK"}},
                "tags": ["(rpc) canmodify"]
            },
            "post": {
                "parameters": [{
                    "in": "body",
                    "name": "args",
                    "required": true,
                    "schema": {
                        "properties": {"": {"format": "text", "type": "string"}},
                        "required": [""],
                        "type": "object"
                    }
                }, {"$ref": "#/parameters/preferParams"}],
                "produces": ["application/json", "application/vnd.pgrst.object+json;nulls=stripped", "application/vnd.pgrst.object+json"],
                "responses": {"200": {"description": "OK"}},
                "tags": ["(rpc) canmodify"]
            }
        },
        "/rpc/is_school_admin": {
            "get": {
                "parameters": [{
                    "format": "uuid",
                    "in": "query",
                    "name": "school_id",
                    "required": true,
                    "type": "string"
                }],
                "produces": ["application/json", "application/vnd.pgrst.object+json;nulls=stripped", "application/vnd.pgrst.object+json"],
                "responses": {"200": {"description": "OK"}},
                "tags": ["(rpc) is_school_admin"]
            },
            "post": {
                "parameters": [{
                    "in": "body",
                    "name": "args",
                    "required": true,
                    "schema": {
                        "properties": {"school_id": {"format": "uuid", "type": "string"}},
                        "required": ["school_id"],
                        "type": "object"
                    }
                }, {"$ref": "#/parameters/preferParams"}],
                "produces": ["application/json", "application/vnd.pgrst.object+json;nulls=stripped", "application/vnd.pgrst.object+json"],
                "responses": {"200": {"description": "OK"}},
                "tags": ["(rpc) is_school_admin"]
            }
        },
        "/rpc/is_admin": {
            "get": {
                "produces": ["application/json", "application/vnd.pgrst.object+json;nulls=stripped", "application/vnd.pgrst.object+json"],
                "responses": {"200": {"description": "OK"}},
                "tags": ["(rpc) is_admin"]
            },
            "post": {
                "parameters": [{
                    "in": "body",
                    "name": "args",
                    "required": true,
                    "schema": {"type": "object"}
                }, {"$ref": "#/parameters/preferParams"}],
                "produces": ["application/json", "application/vnd.pgrst.object+json;nulls=stripped", "application/vnd.pgrst.object+json"],
                "responses": {"200": {"description": "OK"}},
                "tags": ["(rpc) is_admin"]
            }
        }
    },
    "definitions": {
        "orderline": {
            "description": "Bestillinger",
            "required": ["id", "owner_id", "name", "number_of_items"],
            "properties": {
                "id": {
                    "default": "gen_random_uuid()",
                    "description": "Note:\nThis is a Primary Key.<pk/>",
                    "format": "uuid",
                    "type": "string"
                },
                "owner_id": {
                    "default": "auth.uid()",
                    "description": "Note:\nThis is a Foreign Key to `user.id`.<fk table='user' column='id'/>",
                    "format": "uuid",
                    "type": "string"
                },
                "name": {"format": "text", "type": "string"},
                "address": {"format": "text", "type": "string"},
                "number_of_items": {"format": "integer", "type": "integer"},
                "notes": {"format": "text", "type": "string"}
            },
            "type": "object"
        },
        "item": {
            "description": "Gjenstand",
            "required": ["id", "name", "location"],
            "properties": {
                "id": {
                    "description": "Note:\nThis is a Primary Key.<pk/>",
                    "format": "integer",
                    "type": "integer"
                },
                "name": {"format": "character varying", "type": "string"},
                "location": {
                    "description": "Current location\n\nNote:\nThis is a Foreign Key to `location.id`.<fk table='location' column='id'/>",
                    "format": "integer",
                    "type": "integer"
                }
            },
            "type": "object"
        },
        "lyrics": {
            "description": "Sangtekster",
            "required": ["id", "has_chords", "songtitle"],
            "properties": {
                "id": {
                    "description": "Note:\nThis is a Primary Key.<pk/>",
                    "format": "integer",
                    "type": "integer"
                },
                "has_chords": {"format": "boolean", "type": "boolean"},
                "lyrics": {"format": "text", "type": "string"},
                "songtitle": {"format": "text", "type": "string"},
                "artist": {"format": "text", "type": "string"}
            },
            "type": "object"
        },
        "participant_statistics": {
            "description": "Deltager-statistikk",
            "properties": {
                "rvsp_party": {"format": "character varying", "type": "string"},
                "count": {"format": "bigint", "type": "integer"}
            },
            "type": "object"
        },
        "mytable2": {
            "required": ["id"],
            "properties": {
                "id": {
                    "description": "Note:\nThis is a Primary Key.<pk/>",
                    "format": "integer",
                    "type": "integer"
                }, "col2": {"format": "text", "type": "string"}, "col3": {"format": "text", "type": "string"}
            },
            "type": "object"
        },
        "employment": {
            "description": "Ansettelse",
            "required": ["id", "teacher_id", "school_id"],
            "properties": {
                "id": {
                    "default": "gen_random_uuid()",
                    "description": "Note:\nThis is a Primary Key.<pk/>",
                    "format": "uuid",
                    "type": "string"
                },
                "teacher_id": {
                    "description": "Note:\nThis is a Foreign Key to `user.id`.<fk table='user' column='id'/>",
                    "format": "uuid",
                    "type": "string"
                },
                "school_id": {
                    "description": "Note:\nThis is a Foreign Key to `school.id`.<fk table='school' column='id'/>",
                    "format": "uuid",
                    "type": "string"
                }
            },
            "type": "object"
        },
        "school": {
            "description": "Skoler",
            "required": ["id"],
            "properties": {
                "id": {
                    "default": "gen_random_uuid()",
                    "description": "Note:\nThis is a Primary Key.<pk/>",
                    "format": "uuid",
                    "type": "string"
                }, "name": {"format": "text", "type": "string"}
            },
            "type": "object"
        },
        "answer": {
            "description": "Besvarelse",
            "required": ["id", "student_id", "question_id", "points", "questionnaire_id"],
            "properties": {
                "id": {
                    "description": "Note:\nThis is a Primary Key.<pk/>",
                    "format": "integer",
                    "type": "integer"
                },
                "student_id": {
                    "description": "Note:\nThis is a Foreign Key to `student.id`.<fk table='student' column='id'/>",
                    "format": "integer",
                    "type": "integer"
                },
                "question_id": {
                    "description": "Note:\nThis is a Foreign Key to `question.id`.<fk table='question' column='id'/>",
                    "format": "integer",
                    "type": "integer"
                },
                "points": {"format": "numeric", "type": "number"},
                "comments": {"format": "character varying", "maxLength": 512, "type": "string"},
                "questionnaire_id": {
                    "description": "Note:\nThis is a Foreign Key to `questionnaire.id`.<fk table='questionnaire' column='id'/>",
                    "format": "integer",
                    "type": "integer"
                }
            },
            "type": "object"
        },
        "teacher": {
            "description": "Lærer",
            "required": ["id", "course_id", "teacher_id"],
            "properties": {
                "id": {
                    "default": "gen_random_uuid()",
                    "description": "Note:\nThis is a Primary Key.<pk/>",
                    "format": "uuid",
                    "type": "string"
                },
                "course_id": {
                    "description": "Note:\nThis is a Foreign Key to `course.id`.<fk table='course' column='id'/>",
                    "format": "uuid",
                    "type": "string"
                },
                "teacher_id": {
                    "description": "Note:\nThis is a Foreign Key to `user.id`.<fk table='user' column='id'/>",
                    "format": "uuid",
                    "type": "string"
                }
            },
            "type": "object"
        },
        "student": {
            "description": "Elever",
            "required": ["id", "name", "owner_id"],
            "properties": {
                "id": {
                    "description": "Note:\nThis is a Primary Key.<pk/>",
                    "format": "integer",
                    "type": "integer"
                },
                "name": {"format": "text", "type": "string"},
                "comments": {"format": "text", "type": "string"},
                "owner_id": {
                    "description": "Note:\nThis is a Foreign Key to `user.id`.<fk table='user' column='id'/>",
                    "format": "uuid",
                    "type": "string"
                }
            },
            "type": "object"
        },
        "ceremony_statistics": {
            "description": "Deltager-statistikk",
            "properties": {
                "rvsp_ceremony": {"format": "character varying", "type": "string"},
                "count": {"format": "bigint", "type": "integer"}
            },
            "type": "object"
        },
        "course": {
            "description": "Kurs",
            "required": ["id", "school_id"],
            "properties": {
                "id": {
                    "default": "gen_random_uuid()",
                    "description": "Note:\nThis is a Primary Key.<pk/>",
                    "format": "uuid",
                    "type": "string"
                },
                "school_id": {
                    "description": "Note:\nThis is a Foreign Key to `school.id`.<fk table='school' column='id'/>",
                    "format": "uuid",
                    "type": "string"
                },
                "name": {"format": "text", "type": "string"}
            },
            "type": "object"
        },
        "user": {
            "properties": {
                "id": {
                    "description": "Note:\nThis is a Primary Key.<pk/>",
                    "format": "uuid",
                    "type": "string"
                },
                "email": {"format": "character varying", "maxLength": 255, "type": "string"},
                "role": {"format": "character varying", "maxLength": 255, "type": "string"}
            }, "type": "object"
        },
        "assignment": {
            "description": "Lekser",
            "required": ["id", "enrollment_id", "title"],
            "properties": {
                "id": {
                    "default": "gen_random_uuid()",
                    "description": "Note:\nThis is a Primary Key.<pk/>",
                    "format": "uuid",
                    "type": "string"
                },
                "enrollment_id": {
                    "description": "Note:\nThis is a Foreign Key to `enrollment.id`.<fk table='enrollment' column='id'/>",
                    "format": "uuid",
                    "type": "string"
                },
                "status": {"format": "character varying", "maxLength": 128, "type": "string"},
                "title": {"format": "text", "type": "string"},
                "description": {"format": "text", "type": "string"},
                "attachment": {"format": "bytea", "type": "string"}
            },
            "type": "object"
        },
        "questionnaire": {
            "description": "Prøver",
            "required": ["id", "owner_id"],
            "properties": {
                "id": {
                    "description": "Note:\nThis is a Primary Key.<pk/>",
                    "format": "integer",
                    "type": "integer"
                },
                "name": {"format": "text", "type": "string"},
                "owner_id": {
                    "description": "Note:\nThis is a Foreign Key to `user.id`.<fk table='user' column='id'/>",
                    "format": "uuid",
                    "type": "string"
                }
            },
            "type": "object"
        },
        "profiles": {
            "description": "Brukerprofiler",
            "required": ["id"],
            "properties": {
                "id": {
                    "description": "Note:\nThis is a Primary Key.<pk/>",
                    "format": "uuid",
                    "type": "string"
                },
                "updated_at": {"format": "timestamp with time zone", "type": "string"},
                "username": {"format": "text", "type": "string"},
                "avatar_url": {"format": "text", "type": "string"},
                "website": {"format": "text", "type": "string"}
            },
            "type": "object"
        },
        "question": {
            "description": "Spørsmål",
            "required": ["id", "name", "points", "questionnaire_id"],
            "properties": {
                "id": {
                    "description": "Note:\nThis is a Primary Key.<pk/>",
                    "format": "integer",
                    "type": "integer"
                },
                "name": {"format": "text", "type": "string"},
                "comments": {"format": "text", "type": "string"},
                "points": {"format": "integer", "type": "integer"},
                "questionnaire_id": {
                    "description": "Note:\nThis is a Foreign Key to `questionnaire.id`.<fk table='questionnaire' column='id'/>",
                    "format": "integer",
                    "type": "integer"
                }
            },
            "type": "object"
        },
        "participant": {
            "description": "Deltagere",
            "required": ["id"],
            "properties": {
                "id": {
                    "description": "Note:\nThis is a Primary Key.<pk/>",
                    "format": "integer",
                    "type": "integer"
                },
                "name": {"description": "Navn", "format": "character varying", "type": "string"},
                "email": {"format": "character varying", "type": "string"},
                "description": {"format": "character varying", "type": "string"},
                "tasks": {"format": "character varying", "type": "string"},
                "rvsp_ceremony": {"format": "character varying", "type": "string"},
                "sort_order": {"format": "character varying", "type": "string"},
                "rvsp_party": {"format": "character varying", "type": "string"},
                "phone_number": {"format": "character varying", "maxLength": 8, "type": "string"}
            },
            "type": "object"
        },
        "orderline_statistics": {
            "description": "Bestillingsstatistikk",
            "properties": {
                "label": {"format": "text", "type": "string"},
                "number_of_items": {"format": "bigint", "type": "integer"},
                "unit": {"format": "text", "type": "string"},
                "amount_pr_item": {"format": "integer", "type": "integer"},
                "total_amount": {"format": "bigint", "type": "integer"}
            },
            "type": "object"
        },
        "mytable": {
            "required": ["id"],
            "properties": {
                "id": {
                    "description": "Note:\nThis is a Primary Key.<pk/>",
                    "format": "integer",
                    "type": "integer"
                }, "task": {"format": "text", "type": "string"}, "is_done": {"format": "boolean", "type": "boolean"}
            },
            "type": "object"
        },
        "enrollment": {
            "description": "Deltagelse",
            "required": ["id", "student_id", "course_id"],
            "properties": {
                "id": {
                    "default": "gen_random_uuid()",
                    "description": "Note:\nThis is a Primary Key.<pk/>",
                    "format": "uuid",
                    "type": "string"
                },
                "student_id": {
                    "description": "Note:\nThis is a Foreign Key to `user.id`.<fk table='user' column='id'/>",
                    "format": "uuid",
                    "type": "string"
                },
                "course_id": {
                    "description": "Note:\nThis is a Foreign Key to `course.id`.<fk table='course' column='id'/>",
                    "format": "uuid",
                    "type": "string"
                }
            },
            "type": "object"
        },
        "location": {
            "description": "Lokasjoner",
            "required": ["id", "name"],
            "properties": {
                "id": {
                    "description": "Note:\nThis is a Primary Key.<pk/>",
                    "format": "integer",
                    "type": "integer"
                }, "name": {"format": "character varying", "type": "string"}
            },
            "type": "object"
        },
        "countries": {
            "description": "Full list of countries.",
            "required": ["id", "iso2"],
            "properties": {
                "id": {
                    "description": "Note:\nThis is a Primary Key.<pk/>",
                    "format": "bigint",
                    "type": "integer"
                },
                "name": {"description": "Full country name.", "format": "text", "type": "string"},
                "iso2": {"description": "ISO 3166-1 alpha-2 code.", "format": "text", "type": "string"},
                "iso3": {"description": "ISO 3166-1 alpha-3 code.", "format": "text", "type": "string"},
                "local_name": {"description": "Local variation of the name.", "format": "text", "type": "string"},
                "continent": {
                    "enum": ["Africa", "Antarctica", "Asia", "Europe", "Oceania", "North America", "South America"],
                    "format": "public.continents",
                    "type": "string"
                }
            },
            "type": "object"
        }
    },
    "parameters": {
        "preferParams": {
            "name": "Prefer",
            "description": "Preference",
            "required": false,
            "enum": ["params=single-object"],
            "in": "header",
            "type": "string"
        },
        "preferReturn": {
            "name": "Prefer",
            "description": "Preference",
            "required": false,
            "enum": ["return=representation", "return=minimal", "return=none"],
            "in": "header",
            "type": "string"
        },
        "preferCount": {
            "name": "Prefer",
            "description": "Preference",
            "required": false,
            "enum": ["count=none"],
            "in": "header",
            "type": "string"
        },
        "preferPost": {
            "name": "Prefer",
            "description": "Preference",
            "required": false,
            "enum": ["return=representation", "return=minimal", "return=none", "resolution=ignore-duplicates", "resolution=merge-duplicates"],
            "in": "header",
            "type": "string"
        },
        "select": {
            "name": "select",
            "description": "Filtering Columns",
            "required": false,
            "in": "query",
            "type": "string"
        },
        "on_conflict": {
            "name": "on_conflict",
            "description": "On Conflict",
            "required": false,
            "in": "query",
            "type": "string"
        },
        "order": {"name": "order", "description": "Ordering", "required": false, "in": "query", "type": "string"},
        "range": {
            "name": "Range",
            "description": "Limiting and Pagination",
            "required": false,
            "in": "header",
            "type": "string"
        },
        "rangeUnit": {
            "name": "Range-Unit",
            "description": "Limiting and Pagination",
            "required": false,
            "default": "items",
            "in": "header",
            "type": "string"
        },
        "offset": {
            "name": "offset",
            "description": "Limiting and Pagination",
            "required": false,
            "in": "query",
            "type": "string"
        },
        "limit": {
            "name": "limit",
            "description": "Limiting and Pagination",
            "required": false,
            "in": "query",
            "type": "string"
        },
        "body.orderline": {
            "name": "orderline",
            "description": "orderline",
            "required": false,
            "in": "body",
            "schema": {"$ref": "#/definitions/orderline"}
        },
        "rowFilter.orderline.id": {"name": "id", "required": false, "format": "uuid", "in": "query", "type": "string"},
        "rowFilter.orderline.owner_id": {
            "name": "owner_id",
            "required": false,
            "format": "uuid",
            "in": "query",
            "type": "string"
        },
        "rowFilter.orderline.name": {
            "name": "name",
            "required": false,
            "format": "text",
            "in": "query",
            "type": "string"
        },
        "rowFilter.orderline.address": {
            "name": "address",
            "required": false,
            "format": "text",
            "in": "query",
            "type": "string"
        },
        "rowFilter.orderline.number_of_items": {
            "name": "number_of_items",
            "required": false,
            "format": "integer",
            "in": "query",
            "type": "string"
        },
        "rowFilter.orderline.notes": {
            "name": "notes",
            "required": false,
            "format": "text",
            "in": "query",
            "type": "string"
        },
        "body.item": {
            "name": "item",
            "description": "item",
            "required": false,
            "in": "body",
            "schema": {"$ref": "#/definitions/item"}
        },
        "rowFilter.item.id": {"name": "id", "required": false, "format": "integer", "in": "query", "type": "string"},
        "rowFilter.item.name": {
            "name": "name",
            "required": false,
            "format": "character varying",
            "in": "query",
            "type": "string"
        },
        "rowFilter.item.location": {
            "name": "location",
            "description": "Current location",
            "required": false,
            "format": "integer",
            "in": "query",
            "type": "string"
        },
        "body.lyrics": {
            "name": "lyrics",
            "description": "lyrics",
            "required": false,
            "in": "body",
            "schema": {"$ref": "#/definitions/lyrics"}
        },
        "rowFilter.lyrics.id": {"name": "id", "required": false, "format": "integer", "in": "query", "type": "string"},
        "rowFilter.lyrics.has_chords": {
            "name": "has_chords",
            "required": false,
            "format": "boolean",
            "in": "query",
            "type": "string"
        },
        "rowFilter.lyrics.lyrics": {
            "name": "lyrics",
            "required": false,
            "format": "text",
            "in": "query",
            "type": "string"
        },
        "rowFilter.lyrics.songtitle": {
            "name": "songtitle",
            "required": false,
            "format": "text",
            "in": "query",
            "type": "string"
        },
        "rowFilter.lyrics.artist": {
            "name": "artist",
            "required": false,
            "format": "text",
            "in": "query",
            "type": "string"
        },
        "body.participant_statistics": {
            "name": "participant_statistics",
            "description": "participant_statistics",
            "required": false,
            "in": "body",
            "schema": {"$ref": "#/definitions/participant_statistics"}
        },
        "rowFilter.participant_statistics.rvsp_party": {
            "name": "rvsp_party",
            "required": false,
            "format": "character varying",
            "in": "query",
            "type": "string"
        },
        "rowFilter.participant_statistics.count": {
            "name": "count",
            "required": false,
            "format": "bigint",
            "in": "query",
            "type": "string"
        },
        "body.mytable2": {
            "name": "mytable2",
            "description": "mytable2",
            "required": false,
            "in": "body",
            "schema": {"$ref": "#/definitions/mytable2"}
        },
        "rowFilter.mytable2.id": {
            "name": "id",
            "required": false,
            "format": "integer",
            "in": "query",
            "type": "string"
        },
        "rowFilter.mytable2.col2": {
            "name": "col2",
            "required": false,
            "format": "text",
            "in": "query",
            "type": "string"
        },
        "rowFilter.mytable2.col3": {
            "name": "col3",
            "required": false,
            "format": "text",
            "in": "query",
            "type": "string"
        },
        "body.employment": {
            "name": "employment",
            "description": "employment",
            "required": false,
            "in": "body",
            "schema": {"$ref": "#/definitions/employment"}
        },
        "rowFilter.employment.id": {"name": "id", "required": false, "format": "uuid", "in": "query", "type": "string"},
        "rowFilter.employment.teacher_id": {
            "name": "teacher_id",
            "required": false,
            "format": "uuid",
            "in": "query",
            "type": "string"
        },
        "rowFilter.employment.school_id": {
            "name": "school_id",
            "required": false,
            "format": "uuid",
            "in": "query",
            "type": "string"
        },
        "body.school": {
            "name": "school",
            "description": "school",
            "required": false,
            "in": "body",
            "schema": {"$ref": "#/definitions/school"}
        },
        "rowFilter.school.id": {"name": "id", "required": false, "format": "uuid", "in": "query", "type": "string"},
        "rowFilter.school.name": {"name": "name", "required": false, "format": "text", "in": "query", "type": "string"},
        "body.answer": {
            "name": "answer",
            "description": "answer",
            "required": false,
            "in": "body",
            "schema": {"$ref": "#/definitions/answer"}
        },
        "rowFilter.answer.id": {"name": "id", "required": false, "format": "integer", "in": "query", "type": "string"},
        "rowFilter.answer.student_id": {
            "name": "student_id",
            "required": false,
            "format": "integer",
            "in": "query",
            "type": "string"
        },
        "rowFilter.answer.question_id": {
            "name": "question_id",
            "required": false,
            "format": "integer",
            "in": "query",
            "type": "string"
        },
        "rowFilter.answer.points": {
            "name": "points",
            "required": false,
            "format": "numeric",
            "in": "query",
            "type": "string"
        },
        "rowFilter.answer.comments": {
            "name": "comments",
            "required": false,
            "format": "character varying",
            "in": "query",
            "type": "string"
        },
        "rowFilter.answer.questionnaire_id": {
            "name": "questionnaire_id",
            "required": false,
            "format": "integer",
            "in": "query",
            "type": "string"
        },
        "body.teacher": {
            "name": "teacher",
            "description": "teacher",
            "required": false,
            "in": "body",
            "schema": {"$ref": "#/definitions/teacher"}
        },
        "rowFilter.teacher.id": {"name": "id", "required": false, "format": "uuid", "in": "query", "type": "string"},
        "rowFilter.teacher.course_id": {
            "name": "course_id",
            "required": false,
            "format": "uuid",
            "in": "query",
            "type": "string"
        },
        "rowFilter.teacher.teacher_id": {
            "name": "teacher_id",
            "required": false,
            "format": "uuid",
            "in": "query",
            "type": "string"
        },
        "body.student": {
            "name": "student",
            "description": "student",
            "required": false,
            "in": "body",
            "schema": {"$ref": "#/definitions/student"}
        },
        "rowFilter.student.id": {"name": "id", "required": false, "format": "integer", "in": "query", "type": "string"},
        "rowFilter.student.name": {
            "name": "name",
            "required": false,
            "format": "text",
            "in": "query",
            "type": "string"
        },
        "rowFilter.student.comments": {
            "name": "comments",
            "required": false,
            "format": "text",
            "in": "query",
            "type": "string"
        },
        "rowFilter.student.owner_id": {
            "name": "owner_id",
            "required": false,
            "format": "uuid",
            "in": "query",
            "type": "string"
        },
        "body.ceremony_statistics": {
            "name": "ceremony_statistics",
            "description": "ceremony_statistics",
            "required": false,
            "in": "body",
            "schema": {"$ref": "#/definitions/ceremony_statistics"}
        },
        "rowFilter.ceremony_statistics.rvsp_ceremony": {
            "name": "rvsp_ceremony",
            "required": false,
            "format": "character varying",
            "in": "query",
            "type": "string"
        },
        "rowFilter.ceremony_statistics.count": {
            "name": "count",
            "required": false,
            "format": "bigint",
            "in": "query",
            "type": "string"
        },
        "body.course": {
            "name": "course",
            "description": "course",
            "required": false,
            "in": "body",
            "schema": {"$ref": "#/definitions/course"}
        },
        "rowFilter.course.id": {"name": "id", "required": false, "format": "uuid", "in": "query", "type": "string"},
        "rowFilter.course.school_id": {
            "name": "school_id",
            "required": false,
            "format": "uuid",
            "in": "query",
            "type": "string"
        },
        "rowFilter.course.name": {"name": "name", "required": false, "format": "text", "in": "query", "type": "string"},
        "body.user": {
            "name": "user",
            "description": "user",
            "required": false,
            "in": "body",
            "schema": {"$ref": "#/definitions/user"}
        },
        "rowFilter.user.id": {"name": "id", "required": false, "format": "uuid", "in": "query", "type": "string"},
        "rowFilter.user.email": {
            "name": "email",
            "required": false,
            "format": "character varying",
            "in": "query",
            "type": "string"
        },
        "rowFilter.user.role": {
            "name": "role",
            "required": false,
            "format": "character varying",
            "in": "query",
            "type": "string"
        },
        "body.assignment": {
            "name": "assignment",
            "description": "assignment",
            "required": false,
            "in": "body",
            "schema": {"$ref": "#/definitions/assignment"}
        },
        "rowFilter.assignment.id": {"name": "id", "required": false, "format": "uuid", "in": "query", "type": "string"},
        "rowFilter.assignment.enrollment_id": {
            "name": "enrollment_id",
            "required": false,
            "format": "uuid",
            "in": "query",
            "type": "string"
        },
        "rowFilter.assignment.status": {
            "name": "status",
            "required": false,
            "format": "character varying",
            "in": "query",
            "type": "string"
        },
        "rowFilter.assignment.title": {
            "name": "title",
            "required": false,
            "format": "text",
            "in": "query",
            "type": "string"
        },
        "rowFilter.assignment.description": {
            "name": "description",
            "required": false,
            "format": "text",
            "in": "query",
            "type": "string"
        },
        "rowFilter.assignment.attachment": {
            "name": "attachment",
            "required": false,
            "format": "bytea",
            "in": "query",
            "type": "string"
        },
        "body.questionnaire": {
            "name": "questionnaire",
            "description": "questionnaire",
            "required": false,
            "in": "body",
            "schema": {"$ref": "#/definitions/questionnaire"}
        },
        "rowFilter.questionnaire.id": {
            "name": "id",
            "required": false,
            "format": "integer",
            "in": "query",
            "type": "string"
        },
        "rowFilter.questionnaire.name": {
            "name": "name",
            "required": false,
            "format": "text",
            "in": "query",
            "type": "string"
        },
        "rowFilter.questionnaire.owner_id": {
            "name": "owner_id",
            "required": false,
            "format": "uuid",
            "in": "query",
            "type": "string"
        },
        "body.profiles": {
            "name": "profiles",
            "description": "profiles",
            "required": false,
            "in": "body",
            "schema": {"$ref": "#/definitions/profiles"}
        },
        "rowFilter.profiles.id": {"name": "id", "required": false, "format": "uuid", "in": "query", "type": "string"},
        "rowFilter.profiles.updated_at": {
            "name": "updated_at",
            "required": false,
            "format": "timestamp with time zone",
            "in": "query",
            "type": "string"
        },
        "rowFilter.profiles.username": {
            "name": "username",
            "required": false,
            "format": "text",
            "in": "query",
            "type": "string"
        },
        "rowFilter.profiles.avatar_url": {
            "name": "avatar_url",
            "required": false,
            "format": "text",
            "in": "query",
            "type": "string"
        },
        "rowFilter.profiles.website": {
            "name": "website",
            "required": false,
            "format": "text",
            "in": "query",
            "type": "string"
        },
        "body.question": {
            "name": "question",
            "description": "question",
            "required": false,
            "in": "body",
            "schema": {"$ref": "#/definitions/question"}
        },
        "rowFilter.question.id": {
            "name": "id",
            "required": false,
            "format": "integer",
            "in": "query",
            "type": "string"
        },
        "rowFilter.question.name": {
            "name": "name",
            "required": false,
            "format": "text",
            "in": "query",
            "type": "string"
        },
        "rowFilter.question.comments": {
            "name": "comments",
            "required": false,
            "format": "text",
            "in": "query",
            "type": "string"
        },
        "rowFilter.question.points": {
            "name": "points",
            "required": false,
            "format": "integer",
            "in": "query",
            "type": "string"
        },
        "rowFilter.question.questionnaire_id": {
            "name": "questionnaire_id",
            "required": false,
            "format": "integer",
            "in": "query",
            "type": "string"
        },
        "body.participant": {
            "name": "participant",
            "description": "participant",
            "required": false,
            "in": "body",
            "schema": {"$ref": "#/definitions/participant"}
        },
        "rowFilter.participant.id": {
            "name": "id",
            "required": false,
            "format": "integer",
            "in": "query",
            "type": "string"
        },
        "rowFilter.participant.name": {
            "name": "name",
            "description": "Navn",
            "required": false,
            "format": "character varying",
            "in": "query",
            "type": "string"
        },
        "rowFilter.participant.email": {
            "name": "email",
            "required": false,
            "format": "character varying",
            "in": "query",
            "type": "string"
        },
        "rowFilter.participant.description": {
            "name": "description",
            "required": false,
            "format": "character varying",
            "in": "query",
            "type": "string"
        },
        "rowFilter.participant.tasks": {
            "name": "tasks",
            "required": false,
            "format": "character varying",
            "in": "query",
            "type": "string"
        },
        "rowFilter.participant.rvsp_ceremony": {
            "name": "rvsp_ceremony",
            "required": false,
            "format": "character varying",
            "in": "query",
            "type": "string"
        },
        "rowFilter.participant.sort_order": {
            "name": "sort_order",
            "required": false,
            "format": "character varying",
            "in": "query",
            "type": "string"
        },
        "rowFilter.participant.rvsp_party": {
            "name": "rvsp_party",
            "required": false,
            "format": "character varying",
            "in": "query",
            "type": "string"
        },
        "rowFilter.participant.phone_number": {
            "name": "phone_number",
            "required": false,
            "format": "character varying",
            "in": "query",
            "type": "string"
        },
        "body.orderline_statistics": {
            "name": "orderline_statistics",
            "description": "orderline_statistics",
            "required": false,
            "in": "body",
            "schema": {"$ref": "#/definitions/orderline_statistics"}
        },
        "rowFilter.orderline_statistics.label": {
            "name": "label",
            "required": false,
            "format": "text",
            "in": "query",
            "type": "string"
        },
        "rowFilter.orderline_statistics.number_of_items": {
            "name": "number_of_items",
            "required": false,
            "format": "bigint",
            "in": "query",
            "type": "string"
        },
        "rowFilter.orderline_statistics.unit": {
            "name": "unit",
            "required": false,
            "format": "text",
            "in": "query",
            "type": "string"
        },
        "rowFilter.orderline_statistics.amount_pr_item": {
            "name": "amount_pr_item",
            "required": false,
            "format": "integer",
            "in": "query",
            "type": "string"
        },
        "rowFilter.orderline_statistics.total_amount": {
            "name": "total_amount",
            "required": false,
            "format": "bigint",
            "in": "query",
            "type": "string"
        },
        "body.mytable": {
            "name": "mytable",
            "description": "mytable",
            "required": false,
            "in": "body",
            "schema": {"$ref": "#/definitions/mytable"}
        },
        "rowFilter.mytable.id": {"name": "id", "required": false, "format": "integer", "in": "query", "type": "string"},
        "rowFilter.mytable.task": {
            "name": "task",
            "required": false,
            "format": "text",
            "in": "query",
            "type": "string"
        },
        "rowFilter.mytable.is_done": {
            "name": "is_done",
            "required": false,
            "format": "boolean",
            "in": "query",
            "type": "string"
        },
        "body.enrollment": {
            "name": "enrollment",
            "description": "enrollment",
            "required": false,
            "in": "body",
            "schema": {"$ref": "#/definitions/enrollment"}
        },
        "rowFilter.enrollment.id": {"name": "id", "required": false, "format": "uuid", "in": "query", "type": "string"},
        "rowFilter.enrollment.student_id": {
            "name": "student_id",
            "required": false,
            "format": "uuid",
            "in": "query",
            "type": "string"
        },
        "rowFilter.enrollment.course_id": {
            "name": "course_id",
            "required": false,
            "format": "uuid",
            "in": "query",
            "type": "string"
        },
        "body.location": {
            "name": "location",
            "description": "location",
            "required": false,
            "in": "body",
            "schema": {"$ref": "#/definitions/location"}
        },
        "rowFilter.location.id": {
            "name": "id",
            "required": false,
            "format": "integer",
            "in": "query",
            "type": "string"
        },
        "rowFilter.location.name": {
            "name": "name",
            "required": false,
            "format": "character varying",
            "in": "query",
            "type": "string"
        },
        "body.countries": {
            "name": "countries",
            "description": "countries",
            "required": false,
            "in": "body",
            "schema": {"$ref": "#/definitions/countries"}
        },
        "rowFilter.countries.id": {
            "name": "id",
            "required": false,
            "format": "bigint",
            "in": "query",
            "type": "string"
        },
        "rowFilter.countries.name": {
            "name": "name",
            "description": "Full country name.",
            "required": false,
            "format": "text",
            "in": "query",
            "type": "string"
        },
        "rowFilter.countries.iso2": {
            "name": "iso2",
            "description": "ISO 3166-1 alpha-2 code.",
            "required": false,
            "format": "text",
            "in": "query",
            "type": "string"
        },
        "rowFilter.countries.iso3": {
            "name": "iso3",
            "description": "ISO 3166-1 alpha-3 code.",
            "required": false,
            "format": "text",
            "in": "query",
            "type": "string"
        },
        "rowFilter.countries.local_name": {
            "name": "local_name",
            "description": "Local variation of the name.",
            "required": false,
            "format": "text",
            "in": "query",
            "type": "string"
        },
        "rowFilter.countries.continent": {
            "name": "continent",
            "required": false,
            "format": "public.continents",
            "in": "query",
            "type": "string"
        }
    },
    "externalDocs": {"description": "PostgREST Documentation", "url": "https://postgrest.org/en/v12.0/api.html"}
}